spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/toystory;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: TRUE
        format_sql: TRUE

logging:
  level:
    org.hibernate.SQL: debug
